name: kopo
description: find Korea Postal address
version: 0.0.1
author: Paul Han <paul@salondecode.io>
homepage: https://github.com/salondecode/kopo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/daum.html
    - assets/juso.html
